build:
  image: cblomart/rpi-basebuild
  commands:
    - git clone https://github.com/kabukky/journey.git
    - cd journey
    - CC=musl-gcc CCGLAGS="-static" GOOS=linux GOARCH=arm GOARM=5 go build -ldflags '-linkmode external -s -w -extldflags "-static"' -a .
    - cp ./journey ../
    - cd ..
    - git clone https://github.com/kabukky/promenade.git
publish:
  docker:
    username: cblomart
    password: $$DOCKERHUB_PASS
    email: cblomart@gmail.com
    repo: cblomart/rpi-journey
    insecure: true
    tag:
       - $$BRANCH
       - $$COMMIT
       - latest
