build:
  image: cblomart/rpi-basebuild
  commands:
    - CC=musl-gcc CCGLAGS="-static" GOOS=linux GOARCH=arm GOARM=5 go get -ldflags '-linkmode external -s -w -extldflags "-static"' -a  github.com/kabukky/journey
    - cp $(which journey) ./
    - upx -q --brute ./journey
publish:
  docker:
    username: cblomart
    password: $$DOCKERHUB_PASS
    email: cblomart@gmail.com
    repo: cblomart/rpi-journey
    insecure: true
    tag:
       - $$BRANCH
       - $$COMMIT
       - latest
